name: Push
on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - run: nix flake check
      - run: nix develop --command mix deps.get
      - run: nix develop --command mix credo --mute-exit-status -a
      - run: nix develop --command mix test
